# -*- coding: utf-8 -*-
"""8da45fd4-60ad-45f6-9af3-832f4b01b420

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/gcp-hands-on-490407/locations/asia-southeast1/repositories/8da45fd4-60ad-45f6-9af3-832f4b01b420
"""

from google.cloud.dataproc_spark_connect import DataprocSparkSession
from google.cloud.dataproc_v1 import Session

# This will create a default Spark session
spark = DataprocSparkSession.builder.getOrCreate()
# If you would like to customize the Spark session, please refer to the
# documentation at https://cloud.google.com/bigquery/docs/use-spark
#
# For example, if you need to use a different subnetwork, use the code below

# from google.cloud.dataproc_v1 import Session

# session = Session()
# session.environment_config.execution_config.subnetwork_uri = "<subnetwork_name>"
# spark = DataprocSparkSession.builder.dataprocSessionConfig(session).getOrCreate()

# 1. Create a simple list of data
data = [("GCP", 1), ("Spark", 2), ("BigQuery", 3), ("Singapore", 4)]

# 2. Create a DataFrame directly (No sparkContext needed!)
df_test = spark.createDataFrame(data, ["Tech", "Rank"])

# 3. Show the result
df_test.show()

# 1. Create a manual Iris-style dataset
iris_data = [
    (5.1, 3.5, 1.4, 0.2, "setosa"),
    (4.9, 3.0, 1.4, 0.2, "setosa"),
    (7.0, 3.2, 4.7, 1.4, "versicolor"),
    (6.4, 3.2, 4.5, 1.5, "versicolor"),
    (6.3, 3.3, 6.0, 2.5, "virginica")
]

columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]

# 2. Create DataFrame (Spark Connect compatible)
df_iris = spark.createDataFrame(iris_data, columns)

# 3. Show it
df_iris.show()

from google.cloud import bigquery

client = bigquery.Client()
datasets = list(client.list_datasets())

if datasets:
    print(f"Datasets in project {client.project}:")
    for dataset in datasets:
        full_dataset = client.get_dataset(dataset.dataset_id)
        print(f"- ID: {dataset.dataset_id} | Location: {full_dataset.location}")
else:
    print("No datasets found. You need to create one in the Console first!")

# 1. Configuration - Matching your screenshot exactly
PROJECT_ID = "gcp-hands-on-490407"
BUCKET_NAME = "spotify_data_engg"
DATASET_ID = "playground_ds"  # Or your spotify_data_eng if you created it
TABLE_ID = "one_million_tracks_raw"

# 2. Read the CSV using Spark Connect
# inferSchema: Spark will read the first few lines to guess if a column is an Int, Float, or String
spotify_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load(f"gs://{BUCKET_NAME}/spotify_data.csv")

# 3. Quick Data Engineering: Clean Column Names
# BigQuery columns cannot have spaces or special characters
for col_name in spotify_df.columns:
    clean_name = col_name.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_")
    spotify_df = spotify_df.withColumnRenamed(col_name, clean_name)

# 4. Write to BigQuery
try:
    spotify_df.write.format("bigquery") \
        .mode("overwrite") \
        .option("writeMethod", "direct") \
        .save(f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}")

    print(f"🔥 Success! 1.2M records moved from GCS to BigQuery.")
    print(f"Total Rows Processed: {spotify_df.count()}")
except Exception as e:
    print(f"❌ Error during write: {e}")

from google.cloud import bigquery

client = bigquery.Client()
project_id = client.project
dataset_id = "spotify_analysis"  # New name to avoid any 'playground_ds' ghosting
dataset_full_id = f"{project_id}.{dataset_id}"

# 1. Define the dataset object
dataset = bigquery.Dataset(dataset_full_id)
dataset.location = "asia-southeast1"  # Crucial: Must match your GCS and Spark region
dataset.description = "Dataset for Spotify 1.2M records project"

# 2. Create it
try:
    dataset = client.create_dataset(dataset, timeout=30)
    print(f"✅ Created dataset {dataset_id} in {dataset.location}")
except Exception as e:
    print(f"⚠️ Note: {e}")

# 1. Config (Matching your 'spotify_analysis' dataset)
PROJECT_ID = "gcp-hands-on-490407"
BUCKET_NAME = "spotify_data_engg"
TARGET_TABLE = f"{PROJECT_ID}.spotify_analysis.tracks_raw"

# 2. Read from GCS
print("⏳ Reading 175MB CSV from GCS...")
spotify_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load(f"gs://{BUCKET_NAME}/spotify_data.csv")

# 3. Clean column names (BigQuery compatibility)
for col_name in spotify_df.columns:
    clean_name = col_name.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_")
    spotify_df = spotify_df.withColumnRenamed(col_name, clean_name)

# 4. Write to BigQuery
print(f"🚀 Streaming 1.2M records into {TARGET_TABLE}...")
try:
    spotify_df.write.format("bigquery") \
        .mode("overwrite") \
        .option("writeMethod", "direct") \
        .save(TARGET_TABLE)

    print(f"✅ DONE! Ingested {spotify_df.count():,} rows.")
except Exception as e:
    print(f"❌ Snag during the write: {e}")

# Load the raw table from BigQuery
df_inspect = spark.read.format("bigquery").load(f"{PROJECT_ID}.spotify_analysis.tracks_raw")

# Print the schema Spark is using
print("--- ACTUAL SCHEMA ---")
df_inspect.printSchema()

# Show 5 rows to see where the data is actually sitting
print("--- RAW DATA SAMPLE ---")
df_inspect.show(5)

from pyspark.sql.functions import col, expr

# 1. Reference the existing table
raw_df = spark.read.format("bigquery").load(f"{PROJECT_ID}.spotify_analysis.tracks_raw")

# 2. Clean and Filter using try_cast (the safe way)
# This converts '0.85' -> 0.85 and 'german' -> NULL
cleaned_top_tracks = raw_df.select(
    "track_name",
    "artist_name",
    expr("try_cast(danceability AS double)").alias("danceability"),
    expr("try_cast(energy AS double)").alias("energy"),
    expr("try_cast(popularity AS double)").alias("popularity"),
    "genre"
).filter(
    (col("danceability") > 0.8) &
    (col("energy") > 0.8) &
    (col("popularity").isNotNull()) # This naturally drops the shifted rows
).orderBy(col("popularity").desc())

# 3. Final Result
print("Top 10 High-Energy Dance Tracks (Cleaned):")
cleaned_top_tracks.show(10)

# 1. Ensure the table name is defined
TARGET_SILVER_TABLE = f"{PROJECT_ID}.spotify_analysis.tracks_silver"

# 2. Use the correct variable name: 'cleaned_top_tracks'
print(f"💾 Materializing cleaned data to {TARGET_SILVER_TABLE}...")

try:
    cleaned_top_tracks.write.format("bigquery") \
        .mode("overwrite") \
        .option("writeMethod", "direct") \
        .save(TARGET_SILVER_TABLE)

    print("✅ Success! Your 'Silver' layer is ready for high-speed querying.")
except Exception as e:
    print(f"❌ Write failed: {e}")

# 1. Read from the Silver table we just created
silver_df = spark.read.format("bigquery").load(f"{PROJECT_ID}.spotify_analysis.tracks_silver")

# 2. Aggregate metrics by Genre
genre_metrics = silver_df.groupBy("genre") \
    .agg(
        {"danceability": "avg", "energy": "avg", "track_name": "count"}
    ) \
    .withColumnRenamed("avg(danceability)", "avg_dance") \
    .withColumnRenamed("avg(energy)", "avg_energy") \
    .withColumnRenamed("count(track_name)", "total_tracks") \
    .filter("total_tracks > 50") \
    .orderBy(col("avg_energy").desc())

print("--- GENRE VIBE CHECK ---")
genre_metrics.show(10)